site_name: TV Anleitung

theme:
  name: material
  features:
    - instant
    - tabs
  logo: img/logo.svg
  favicon: img/logo.svg
  language: de

extra_css:
  - css.css

google_analytics:
  - UA-152802151-3
  - auto

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: index.md
  - TV:
    - TV: tv/index.md
    - TV Overlay: tv/senderinformation.md
    - TV Programm: tv/programm.md
    - Radio: tv/radio.md
    - Aufnahmen: tv/aufnahmen.md
    - Apps: tv/apps.md
    - Einstellungen: tv/einstellungen.md
  - Web:
    - Web App: web/index.md
    #- Guide: web/guide.md
    #- Aufnahmen: web/aufnahmen.md
    #- Replay: web/replay.md
    #- Suchen: web/suchen.md
    #- Einstellungen: web/einstellungen.md
  - Mobile:
    - TV App: mobile/index.md
    - Guide: mobile/guide.md
    - Aufnahmen: mobile/aufnahmen.md
    - Replay: mobile/replay.md
    - Mehr: mobile/mehr.md

plugins:
    - search:
        lang: de
    - pdf-export